sudo: required

services:
    - docker

before_install:
    - docker build -t barrybt23/docker-react -f Dockerfile.dev .

script:
<<<<<<< HEAD
    - docker run barrybt23/docker-react npm test 
=======
    - docker run -e CI=true barrybt23/docker-react npm run test 
>>>>>>> e0aaf9d07d057293aef9e9aeeb3446f99be67aa3
